apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: process-geography
  labels:
      cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: jej_qud_gup
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 497.0.0
        run.googleapis.com/execution-environment: gen2
    spec:
      template:
        spec:
          containers:
          - image: us-central1-docker.pkg.dev/cru-data-orchestration-poc/gcrj-artifacts/process-geography:latest
            env:
            - name: BIGQUERY_PROJECT_NAME
              value: cru-data-warehouse-elt-stage
            - name: BGIQUERY_DATASET_NAME
              value: el_geography
            - name: GEONAMES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: process-geography_GEONAMES_PASSWORD
            - name: GEONAMES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: process-geography_GEONAMES_USERNAME
            - name: MAXMIND_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: process-geography_MAXMIND_LICENSE_KEY
            resources:
              limits:
                memory: 16Gi
                cpu: 4000m
          maxRetries: 1
          timeoutSeconds: '3600'
          serviceAccountName: process-geography-sa@cru-data-orchestration-poc.iam.gserviceaccount.com
