name: Build & Deploy Cloudrun Function Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'fivetran-trigger/**'
  workflow_dispatch:
    inputs:
      function_name:
        description: 'The name of the Cloud Function to deploy'
        required: true
        default: 'fivetran-trigger'
      entry_point:
        description: 'The python function serving as the entry point'
        required: true
        default: 'hello_http'
      runtime:
        description: 'The function runtime'
        required: true
        default: 'python312'

jobs:
  build_and_deploy:

    uses: CruGlobal/.github/.github/workflows/build-deploy-cloudrun-function.yml@gcp-cloudrun #temporarily using branch for testing
    with:
      function_name: ${{ github.event.inputs.function_name }}
      entry_point: hello_http
      runtime: python312
      environment: staging

