name: Build & Deploy Fivetran Trigger

on:
  push:
    branches:
      - main
      - poc
      - staging
    paths:
      - 'fivetran-trigger/**'
  workflow_dispatch:

jobs:
  build_and_deploy_fivetran_trigger:
    uses: CruGlobal/.github/.github/workflows/build-deploy-cloudrun-function.yml@v1
    with:
      function_name: fivetran-trigger
      entry_point: trigger_sync
      runtime: python312
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/poc' && 'poc' || github.ref == 'refs/heads/staging' && 'staging' }}
    secrets:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ vars.GCP_PROJECT_NUMBER }}
      WORKLOAD_IDENTITY_POOL: ${{ vars.WORKLOAD_IDENTITY_POOL }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
      GCP_REGION: ${{ vars.GCP_REGION }}
