name: Build & Deploy Cloudrun Functions

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'fivetran-trigger/**'
  workflow_dispatch:
    inputs:
      function_name:
        description: 'The name of the Cloud Function to deploy'
        required: true
        default: 'fivetran-trigger'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Deploy
        uses: CruGlobal/.github/.github/workflows/build-deploy-cloudrun-function.yml@gcp-cloudrun #temporarily using branch for testing
        with:
          function_name: ${{ github.event.inputs.function_name }}