name: Build & Deploy Cloudrun Function Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'fivetran-trigger/**'
  workflow_dispatch:
    inputs:
      function_name:
        description: 'The name of the Cloud Function to deploy'
        required: true
        default: 'fivetran-trigger'
      entry_point:
        description: 'The python function serving as the entry point'
        required: true
        default: 'hello_http'
      runtime:
        description: 'The function runtime'
        required: true
        default: 'python312'

jobs:
  build_and_deploy:

    uses: CruGlobal/.github/.github/workflows/build-deploy-cloudrun-function.yml@v1
    with:
      function_name: ${{ github.event.inputs.function_name }}
      entry_point: hello_http
      runtime: python312
      environment: staging
    secrets:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ vars.GCP_PROJECT_NUMBER }}
      WORKLOAD_IDENTITY_POOL: ${{ vars.WORKLOAD_IDENTITY_POOL }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
      GCP_REGION: ${{ vars.GCP_REGION }}

