name: Build and Deploy Cloud Run Job

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name:latest .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name:latest

      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs update your-job-name \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-image-name:latest \
            --region ${{ secrets.GCP_REGION }}
